//! Black-box regressions for #392: a `##` section of an agent file used to
//! end at the next heading of **any** level, so the first `###` inside
//! `## System Prompt` / `## Instructions` / `## Output Format` truncated the
//! prompt — silently, with no parse error.
//!
//! These are wiring tests on purpose. The parser's own unit tests (in
//! `armadai-core::parser::markdown`) prove the section boundary; they cannot
//! prove that the un-truncated text actually reaches a model. `link` writes
//! `system_prompt`/`instructions`/`output_format` verbatim into a native
//! config file and `run` hands `system_prompt` to the provider, so both are
//! measured here on the real binary.
//!
//! Measured on `master` before the fix (`armadai link --target claude`, a
//! project holding only `agent-builder.md`): 3833 source bytes in, 1717
//! generated bytes out, zero occurrences of `### Required Structure`.

#[cfg(test)]
mod tests {
    use assert_cmd::Command;
    use std::path::{Path, PathBuf};

    /// Every target CLI the linker supports. The truncation was in the shared
    /// parser, so it hit all five identically — and so must the fix.
    const TARGETS: &[(&str, &str)] = &[
        ("claude", ".claude/agents/nested.md"),
        ("codex", ".codex/agents/nested.toml"),
        ("copilot", ".github/agents/nested.agent.md"),
        ("gemini", ".gemini/agents/nested.md"),
        ("opencode", ".opencode/agents/nested.md"),
    ];

    /// Isolate `~/.config/armadai` per project: `link`/`run` register the
    /// project and scan the global agent library, which on a developer machine
    /// holds real agents that would shadow the fixture.
    fn isolated_config(dir: &Path) -> PathBuf {
        let config = dir.join("config");
        std::fs::create_dir_all(&config).unwrap();
        config
    }

    /// An agent whose every `##` section carries `###` sub-sections. Each
    /// marker is a token nothing else in the repo produces, so an assertion
    /// on it cannot be satisfied by boilerplate the linker emits anyway.
    const NESTED_AGENT: &str = r#"# nested

## Metadata

### Provider
- provider: anthropic
- model: claude-sonnet-4-5-20250929

### Tuning
- temperature: 0.9
- tags: [dev]

## System Prompt

An agent file has these required sections:

### Required Structure

SYSPROMPT_SUBSECTION_MARKER — the list the sentence above announces.

## Instructions

### Phase 1

INSTRUCTIONS_SUBSECTION_MARKER — what to do first.

## Output Format

### Root Cause

OUTPUTFORMAT_SUBSECTION_MARKER — one sentence.
"#;

    fn project_with_nested_agent() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("project");
        std::fs::create_dir_all(root.join("agents")).unwrap();
        std::fs::create_dir_all(root.join(".armadai")).unwrap();
        std::fs::write(
            root.join(".armadai/config.yaml"),
            "agents:\n  - path: agents/nested.md\n",
        )
        .unwrap();
        std::fs::write(root.join("agents/nested.md"), NESTED_AGENT).unwrap();
        dir
    }

    /// The full round trip, per target: source `.md` -> `parse_agent_file` ->
    /// linker -> generated native config. Before the fix each generated file
    /// stopped at the first `###` of every section.
    #[test]
    fn link_keeps_h3_subsections_of_every_section_for_all_targets() {
        for (target, generated) in TARGETS {
            let dir = project_with_nested_agent();
            let root = dir.path().join("project");

            let mut cmd = Command::cargo_bin("armadai").unwrap();
            cmd.current_dir(&root)
                .env("ARMADAI_CONFIG_DIR", isolated_config(dir.path()))
                .args(["link", "--target", target, "--force"]);
            let output = cmd.output().unwrap();
            assert!(
                output.status.success(),
                "link --target {target} failed: {}",
                String::from_utf8_lossy(&output.stderr)
            );

            let path = root.join(generated);
            let content = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));

            for marker in [
                "SYSPROMPT_SUBSECTION_MARKER",
                "INSTRUCTIONS_SUBSECTION_MARKER",
                "OUTPUTFORMAT_SUBSECTION_MARKER",
            ] {
                // Exactly once, not merely "at least once": `contains` alone
                // would also accept the opposite failure, a boundary too
                // permissive (only `#` closing a section), which makes each
                // section swallow the ones below it and every linker emit the
                // same text two or three times over.
                let hits = content.matches(marker).count();
                assert_eq!(
                    hits,
                    1,
                    "target {target}: expected {marker} exactly once in {}, got {hits} \
                     — 0 means a `##` section was truncated at its first `###`, \
                     >1 means a `##` section swallowed the sections below it.\n\
                     --- generated ---\n{content}",
                    path.display()
                );
            }
            // The sub-headings themselves must survive too, not just the text
            // under them: they carry the structure the prompt relies on.
            for heading in ["### Required Structure", "### Phase 1", "### Root Cause"] {
                assert!(
                    content.contains(heading),
                    "target {target}: {heading:?} missing from {}",
                    path.display()
                );
            }
        }
    }

    /// The metadata block is parsed field by field, so the truncation dropped
    /// every field declared after a sub-heading. Proven through the generated
    /// file rather than the parser: `temperature: 0.9` sits under the SECOND
    /// `###` of `## Metadata`, and only `gemini`/`opencode` emit it — so this
    /// is measured on `gemini`, where a lost field is visible in the output.
    #[test]
    fn link_keeps_metadata_fields_declared_after_a_subsection() {
        let dir = project_with_nested_agent();
        let root = dir.path().join("project");

        let mut cmd = Command::cargo_bin("armadai").unwrap();
        cmd.current_dir(&root)
            .env("ARMADAI_CONFIG_DIR", isolated_config(dir.path()))
            .args(["link", "--target", "gemini", "--force"]);
        let output = cmd.output().unwrap();
        assert!(
            output.status.success(),
            "link failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        let content = std::fs::read_to_string(root.join(".gemini/agents/nested.md")).unwrap();
        assert!(
            content.contains("temperature: 0.9"),
            "`temperature` declared under a second `### ` in `## Metadata` was dropped \
             (default 0.7 would be emitted instead).\n--- generated ---\n{content}"
        );
    }

    /// `crates/armadai/templates/debug.md` is shipped with the product and
    /// puts *all* of its `## Instructions` content under `### Phase N`
    /// sub-headings — so `armadai new --template debug` produced, from the
    /// first release, an agent whose Instructions section parsed as the empty
    /// string. The template is read from the repo (not copied into this file)
    /// so the test measures what actually ships.
    #[test]
    fn a_shipped_template_survives_parse_then_link() {
        let template =
            std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/templates/debug.md"))
                .expect("shipped debug.md template");

        // Guard the fixture: if the template ever stops using sub-headings,
        // this test would silently stop testing anything.
        assert!(
            template.contains("### Phase 1: Assessment"),
            "the shipped debug.md template no longer carries `### ` sub-headings — \
             this test no longer measures #392 and must be re-pointed"
        );

        let agent = template
            .replace("{{name}}", "debug-template")
            .replace("{{model}}", "claude-sonnet-4-5-20250929")
            .replace("{{stack}}", "rust");

        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("project");
        std::fs::create_dir_all(root.join("agents")).unwrap();
        std::fs::create_dir_all(root.join(".armadai")).unwrap();
        std::fs::write(
            root.join(".armadai/config.yaml"),
            "agents:\n  - path: agents/debug-template.md\n",
        )
        .unwrap();
        std::fs::write(root.join("agents/debug-template.md"), &agent).unwrap();

        let mut cmd = Command::cargo_bin("armadai").unwrap();
        cmd.current_dir(&root)
            .env("ARMADAI_CONFIG_DIR", isolated_config(dir.path()))
            .args(["link", "--target", "claude", "--force"]);
        let output = cmd.output().unwrap();
        assert!(
            output.status.success(),
            "link failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        let content =
            std::fs::read_to_string(root.join(".claude/agents/debug-template.md")).unwrap();

        // All four phases, headings AND bodies.
        for needle in [
            "### Phase 1: Assessment",
            "Read the error message, stack trace, or bug description",
            "### Phase 2: Investigation",
            "Trace the execution path from input to error",
            "### Phase 3: Resolution",
            "Identify the root cause (not symptoms)",
            "### Phase 4: QA",
            "Describe how to verify the fix works",
        ] {
            assert!(
                content.contains(needle),
                "{needle:?} missing from the linked shipped template \
                 — `## Instructions` was truncated.\n--- generated ---\n{content}"
            );
        }
    }

    /// `run` is the other consumer of the truncated field: the provider gets
    /// `agent.system_prompt` and nothing else. Measured through the real
    /// binary with a `provider: cli` agent whose command echoes back the exact
    /// string it was handed, so stdout *is* the prompt that was sent.
    #[test]
    fn run_sends_the_whole_system_prompt_to_the_provider() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("project");
        std::fs::create_dir_all(root.join("agents")).unwrap();
        std::fs::create_dir_all(root.join(".armadai")).unwrap();

        // `sh <script> <input>`: the CLI provider appends the composed input
        // as the last argument, so `$1` inside the script is verbatim what
        // the provider sent. Invoked via `sh <path>` rather than as an
        // executable so no chmod is needed.
        let script = root.join("echo-prompt.sh");
        std::fs::write(&script, "printf '%s' \"$1\"\n").unwrap();

        std::fs::write(
            root.join("agents/probe.md"),
            format!(
                "# probe\n\n## Metadata\n- provider: cli\n- command: sh\n- args: [{}]\n\n\
                 ## System Prompt\n\nIntro sentence before any sub-heading.\n\n\
                 ### Deep Section\n\nRUN_DEEP_PROMPT_MARKER must reach the provider.\n",
                script.display()
            ),
        )
        .unwrap();
        std::fs::write(
            root.join(".armadai/config.yaml"),
            "agents:\n  - path: agents/probe.md\n",
        )
        .unwrap();

        let mut cmd = Command::cargo_bin("armadai").unwrap();
        cmd.current_dir(&root)
            .env("ARMADAI_CONFIG_DIR", isolated_config(dir.path()))
            // `run` records into SQLite, and `db.rs`'s `#[cfg(test)]` guard does
            // not protect a *spawned* binary. Without this the test writes into
            // the developer's real ~/.local/share/armadai/armadai.sqlite —
            // measured: the `runs` table went from 6 rows to 7, prompt included.
            .env("XDG_DATA_HOME", dir.path().join("data"))
            .args(["run", "probe", "TASK", "--headless"]);
        let output = cmd.output().unwrap();
        let stdout = String::from_utf8_lossy(&output.stdout);
        assert!(
            output.status.success(),
            "run failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        // Sanity: the echo mechanism is actually wired (otherwise the marker
        // assertion below could pass/fail for the wrong reason).
        assert!(
            stdout.contains("Intro sentence before any sub-heading."),
            "the probe command did not echo the prompt back — the test's own \
             mechanism is broken, not the parser.\n--- stdout ---\n{stdout}"
        );
        assert!(
            stdout.contains("RUN_DEEP_PROMPT_MARKER"),
            "the text after the first `### ` never reached the provider.\n\
             --- stdout ---\n{stdout}"
        );
    }
}
